import type { Href } from "expo-router";

export const routes = {
  HOME: "/home",
  ABOUT: "/(pages)/about-us",
  CONTACT: "/(pages)/contact-us",
  SERVICES: "/(pages)/services",
  PORTS: "/(pages)/ports-catered",
  QUOTE: "/(pages)/get-quote",
  APPOINTMENT: "/(pages)/get-appointment",
  AHTN: "/(pages)/ahtn-checker",
  LANDING_PAGE: "/(pages)/landing-page",
  LANDING_PAGE2: "/(pages)/landing-page/customs-brokerage",
  CAREERS: "/(pages)/careers",
  SIGN_IN: "/(pages)/sign-in",
  CLIENT_DB: "/(client)/(tabs)/dashboard",
  CLIENT_AHTN: "/(client)/(tabs)/ahtn-checker",
  CLIENT_CREATE_QUOTE: "/(client)/(tabs)/get-quote",
  CLIENT_QUOTE_DETAILS: "/(client)/(tabs)/dashboard/quotations/[id]",
  CLIENT_REQ_QUOTE_RECORDS: "/(client)/(tabs)/dashboard/requested-quotes",
  CLIENT_RES_QUOTE_RECORDS: "/(client)/(tabs)/dashboard/responded-quotes",
  CLIENT_MESSAGES: "/(client)/(tabs)/messages",
  AS_DB: "/(employee-account-specialist)/(tabs)/dashboard",
  AS_QUOTE_REQUESTS:
    "/(employee-account-specialist)/(tabs)/dashboard/request-quotation",
  AS_AHTN: "/(employee-account-specialist)/(tabs)/ahtn-checker",
  ACCOUNT_SETTINGS: "/account-settings",
  MARKETING_DB: "/(employee-marketing)/dashboard",
  UNAUTHORIZED: "/(pages)/Unauthorized",
  UNDERCONSTRUCTION: "/UnderConstruction",
} as const satisfies Record<string, Href>;
